name: fullstack-challenge
services:
    app:
        build:
            context: ./docker
        ports:
            - "80:80"
            - "8000:8000"
        volumes:
            - .:/var/www/html
        command: php artisan octane:start --watch --workers=2 --server=swoole --host=0.0.0.0 --port=80

    mysql:
        image: mysql:8
        ports:
            - "3306:3306"
        volumes:
            - mysql_data:/var/lib/mysql
            - ./docker:/docker-entrypoint-initdb.d
        environment:
            MYSQL_ROOT_PASSWORD: root

    redis:
        image: redis:7
        ports:
            - "6379:6379"
        volumes:
            - redis_data:/data

    memcached:
        image: memcached:latest
        ports:
            - "11211:11211"
        volumes:
            - memcached_data:/data

volumes:
    mysql_data:
    redis_data:
    memcached_data:
